# Generated by Django 3.0 on 2025-01-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门名称')),
                ('name', models.CharField(max_length=32, verbose_name='emlpoyee name')),
                ('age', models.IntegerField(verbose_name='emlpoyee age')),
                ('email', models.EmailField(max_length=32, verbose_name='emlpoyee email')),
                ('sex', models.CharField(max_length=4, verbose_name='emlpoyee sex')),
                ('phone', models.CharField(max_length=11, verbose_name='emlpoyee phone')),
            ],
        ),
    ]
